using System.Text;

namespace DataToScriptableObject.Editor.Builders
{
    public class CodeFileBuilder
    {
        #region Fields

        private readonly StringBuilder _sb = new StringBuilder();
        private readonly string _namespaceName;
        private int _indentLevel;

        #endregion

        #region Properties

        private string CurrentIndent => new string(' ', _indentLevel * 4);

        #endregion
        
        #region Constructors

        public CodeFileBuilder(string namespaceName = null)
        {
            _namespaceName = namespaceName;
        }
        
        #endregion

        #region Build Methods

        public CodeFileBuilder WithHeader(GenerationSettings settings)
        {
            if (!settings.AddAutoGeneratedHeader) return this;
            
            _sb.AppendLine("// ─────────────────────────────────────────────────────────────");
            _sb.AppendLine("// Auto-generated by Data to ScriptableObject");
            _sb.AppendLine("// This file can be modified. Re-imports match fields by name.");
            _sb.AppendLine("// ─────────────────────────────────────────────────────────────");
            _sb.AppendLine();
            return this;
        }

        public CodeFileBuilder BeginNamespace()
        {
            _sb.AppendLine("using UnityEngine;");
            _sb.AppendLine("using System.Collections.Generic;");
            _sb.AppendLine();
            
            if (string.IsNullOrEmpty(_namespaceName)) return this;
            
            _sb.AppendLine($"namespace {_namespaceName}");
            _sb.AppendLine("{");
            _indentLevel++;
            return this;
        }

        public CodeFileBuilder EndNamespace()
        {
            if (string.IsNullOrEmpty(_namespaceName)) return this;
            
            _indentLevel--;
            _sb.AppendLine("}");
            return this;
        }

        public CodeFileBuilder BeginScriptableObjectClass(string className, GenerationSettings settings)
        {
            if (settings.GenerateCreateAssetMenu)
                _sb.AppendLine($"{CurrentIndent}[CreateAssetMenu(fileName = \"New{className}\", menuName = \"Data/{className}\")]");
            
            _sb.AppendLine($"{CurrentIndent}public class {className} : ScriptableObject");
            _sb.AppendLine($"{CurrentIndent}{{");
            _indentLevel++;
            return this;
        }

        public CodeFileBuilder BeginSerializableClass(string className)
        {
            _sb.AppendLine($"{CurrentIndent}[System.Serializable]");
            _sb.AppendLine($"{CurrentIndent}public class {className}");
            _sb.AppendLine($"{CurrentIndent}{{");
            _indentLevel++;
            return this;
        }

        public CodeFileBuilder EndClass()
        {
            _indentLevel--;
            _sb.AppendLine($"{CurrentIndent}}}");
            return this;
        }

        public CodeFileBuilder AppendLine(string line = "")
        {
            if (string.IsNullOrEmpty(line))
                _sb.AppendLine();
            else
                _sb.AppendLine($"{CurrentIndent}{line}");
            return this;
        }

        public string Build() => _sb.ToString();
        
        #endregion
    }
}