using DataToScriptableObject;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

namespace DataToScriptableObject.Editor
{
    public class CodeGenerationResult
    {
        public string entryClassCode;
        public string databaseClassCode;
        public string entryClassPath;
        public string databaseClassPath;
    }

    public static class CodeGenerator
    {
        public static CodeGenerationResult Generate(TableSchema schema, GenerationSettings settings)
        {
            var result = new CodeGenerationResult();

            Directory.CreateDirectory(settings.scriptOutputPath);

            result.entryClassCode = GenerateScriptableObject(schema, settings);
            result.databaseClassCode = GenerateDatabaseClass(schema, settings);

            string sanitizedClassName = NameSanitizer.SanitizeClassName(schema.className);
            string sanitizedDatabaseName = NameSanitizer.SanitizeClassName(schema.databaseName);

            result.entryClassPath = Path.Combine(settings.scriptOutputPath, $"{sanitizedClassName}.cs");
            result.databaseClassPath = Path.Combine(settings.scriptOutputPath, $"{sanitizedDatabaseName}.cs");

            if (!settings.serializableClassMode)
            {
                File.WriteAllText(result.entryClassPath, result.entryClassCode);
                File.WriteAllText(result.databaseClassPath, result.databaseClassCode);
            }
            else
            {
                var combinedCode = new StringBuilder();
                if (settings.addAutoGeneratedHeader)
                {
                    combinedCode.AppendLine("// ─────────────────────────────────────────────────────────────");
                    combinedCode.AppendLine("// Auto-generated by Data to ScriptableObject");
                    combinedCode.AppendLine("// This file can be modified. Re-imports match fields by name.");
                    combinedCode.AppendLine("// ─────────────────────────────────────────────────────────────");
                    combinedCode.AppendLine();
                }

                combinedCode.AppendLine("using UnityEngine;");
                combinedCode.AppendLine("using System.Collections.Generic;");
                combinedCode.AppendLine();

                if (!string.IsNullOrEmpty(schema.namespaceName))
                {
                    combinedCode.AppendLine($"namespace {schema.namespaceName}");
                    combinedCode.AppendLine("{");
                }

                combinedCode.AppendLine("    [System.Serializable]");
                combinedCode.AppendLine($"    public class {sanitizedClassName}");
                combinedCode.AppendLine("    {");

                foreach (var column in schema.columns.Where(c => !c.isSkipped))
                {
                    AppendFieldDeclaration(combinedCode, column, settings, "        ");
                }

                combinedCode.AppendLine("    }");
                combinedCode.AppendLine();

                if (settings.generateCreateAssetMenu)
                {
                    combinedCode.AppendLine($"    [CreateAssetMenu(fileName = \"New{sanitizedDatabaseName}\", menuName = \"Data/{sanitizedDatabaseName}\")]");
                }
                combinedCode.AppendLine($"    public class {sanitizedDatabaseName} : ScriptableObject");
                combinedCode.AppendLine("    {");
                combinedCode.AppendLine($"        public List<{sanitizedClassName}> entries;");
                combinedCode.AppendLine("    }");

                if (!string.IsNullOrEmpty(schema.namespaceName))
                {
                    combinedCode.AppendLine("}");
                }

                File.WriteAllText(result.databaseClassPath, combinedCode.ToString());
                result.entryClassPath = result.databaseClassPath;
            }

            AssetDatabase.Refresh();

            return result;
        }

        public static string GenerateScriptableObject(TableSchema schema, GenerationSettings settings)
        {
            var sb = new StringBuilder();

            if (settings.addAutoGeneratedHeader)
            {
                sb.AppendLine("// ─────────────────────────────────────────────────────────────");
                sb.AppendLine("// Auto-generated by Data to ScriptableObject");
                sb.AppendLine("// This file can be modified. Re-imports match fields by name.");
                sb.AppendLine("// ─────────────────────────────────────────────────────────────");
                sb.AppendLine();
            }

            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(schema.namespaceName))
            {
                sb.AppendLine($"namespace {schema.namespaceName}");
                sb.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(schema.namespaceName) ? "" : "    ";
            string sanitizedClassName = NameSanitizer.SanitizeClassName(schema.className);

            if (settings.serializableClassMode)
            {
                sb.AppendLine($"{indent}[System.Serializable]");
                sb.AppendLine($"{indent}public class {sanitizedClassName}");
            }
            else
            {
                if (settings.generateCreateAssetMenu)
                {
                    sb.AppendLine($"{indent}[CreateAssetMenu(fileName = \"New{sanitizedClassName}\", menuName = \"Data/{sanitizedClassName}\")]");
                }
                sb.AppendLine($"{indent}public class {sanitizedClassName} : ScriptableObject");
            }

            sb.AppendLine($"{indent}{{");

            foreach (var column in schema.columns.Where(c => !c.isSkipped))
            {
                AppendFieldDeclaration(sb, column, settings, indent + "    ");
            }

            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(schema.namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        public static string GenerateDatabaseClass(TableSchema schema, GenerationSettings settings)
        {
            var sb = new StringBuilder();

            if (settings.addAutoGeneratedHeader)
            {
                sb.AppendLine("// ─────────────────────────────────────────────────────────────");
                sb.AppendLine("// Auto-generated by Data to ScriptableObject");
                sb.AppendLine("// This file can be modified. Re-imports match fields by name.");
                sb.AppendLine("// ─────────────────────────────────────────────────────────────");
                sb.AppendLine();
            }

            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine();

            if (!string.IsNullOrEmpty(schema.namespaceName))
            {
                sb.AppendLine($"namespace {schema.namespaceName}");
                sb.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(schema.namespaceName) ? "" : "    ";
            string sanitizedClassName = NameSanitizer.SanitizeClassName(schema.className);
            string sanitizedDatabaseName = NameSanitizer.SanitizeClassName(schema.databaseName);

            sb.AppendLine($"{indent}[CreateAssetMenu(fileName = \"New{sanitizedDatabaseName}\", menuName = \"Data/{sanitizedDatabaseName}\")]");
            sb.AppendLine($"{indent}public class {sanitizedDatabaseName} : ScriptableObject");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    public List<{sanitizedClassName}> entries;");
            sb.AppendLine($"{indent}}}");

            if (!string.IsNullOrEmpty(schema.namespaceName))
            {
                sb.AppendLine("}");
            }

            return sb.ToString();
        }

        private static void AppendFieldDeclaration(StringBuilder sb, ColumnSchema column, GenerationSettings settings, string indent)
        {
            if (settings.generateTooltips && column.attributes.ContainsKey("tooltip"))
            {
                sb.AppendLine($"{indent}[Tooltip(\"{column.attributes["tooltip"]}\")]");
            }

            if (column.attributes.ContainsKey("range"))
            {
                var rangeParts = column.attributes["range"].Split(',');
                if (rangeParts.Length == 2)
                {
                    sb.AppendLine($"{indent}[Range({rangeParts[0]}f, {rangeParts[1]}f)]");
                }
            }

            if (column.attributes.ContainsKey("hide"))
            {
                sb.AppendLine($"{indent}[HideInInspector]");
            }

            if (column.attributes.ContainsKey("header"))
            {
                sb.AppendLine($"{indent}[Header(\"{column.attributes["header"]}\")]");
            }

            string typeString = GetTypeString(column, settings);

            if (settings.useSerializeField)
            {
                sb.AppendLine($"{indent}[SerializeField] private {typeString} {column.fieldName};");
                
                if (settings.generatePropertyAccessors)
                {
                    string pascalName = char.ToUpperInvariant(column.fieldName[0]) + column.fieldName.Substring(1);
                    sb.AppendLine($"{indent}public {typeString} {pascalName} => {column.fieldName};");
                }
            }
            else
            {
                sb.AppendLine($"{indent}public {typeString} {column.fieldName};");
            }
        }

        private static string GetTypeString(ColumnSchema column, GenerationSettings settings)
        {
            bool useList = column.isList || settings.useListInsteadOfArray;
            string elementType = "";

            switch (column.resolvedType)
            {
                case ResolvedType.Int: return "int";
                case ResolvedType.Float: return "float";
                case ResolvedType.Double: return "double";
                case ResolvedType.Long: return "long";
                case ResolvedType.Bool: return "bool";
                case ResolvedType.String: return "string";
                case ResolvedType.Vector2: return "Vector2";
                case ResolvedType.Vector3: return "Vector3";
                case ResolvedType.Color: return "Color";
                case ResolvedType.Sprite: return "Sprite";
                case ResolvedType.Prefab: return "GameObject";
                case ResolvedType.Asset: return "ScriptableObject";
                case ResolvedType.Enum:
                    string enumName = char.ToUpperInvariant(column.fieldName[0]) + column.fieldName.Substring(1);
                    return enumName;
                case ResolvedType.IntArray:
                    elementType = "int";
                    return useList ? $"List<{elementType}>" : $"{elementType}[]";
                case ResolvedType.FloatArray:
                    elementType = "float";
                    return useList ? $"List<{elementType}>" : $"{elementType}[]";
                case ResolvedType.StringArray:
                    elementType = "string";
                    return useList ? $"List<{elementType}>" : $"{elementType}[]";
                case ResolvedType.BoolArray:
                    elementType = "bool";
                    return useList ? $"List<{elementType}>" : $"{elementType}[]";
                default:
                    return "string";
            }
        }
    }
}
