using NUnit.Framework;
using DataToScriptableObject;
using DataToScriptableObject.Editor;
using System.Linq;

namespace DataToScriptableObject.Tests.Editor
{
    public class CodeGeneratorTests
    {
        private GenerationSettings GetDefaultSettings()
        {
            return new GenerationSettings
            {
                sanitizeFieldNames = true,
                nullToken = "null",
                arraySplitToken = ";",
                useListInsteadOfArray = false,
                useSerializeField = false,
                addCreateAssetMenu = true,
                addAutoGeneratedComment = true,
                generateCreateAssetMenu = true,
                generateTooltips = true,
                scriptOutputPath = "Assets/Scripts/Generated"
            };
        }

        private TableSchema CreateBasicSchema()
        {
            return new TableSchema
            {
                className = "Item",
                databaseName = "ItemDatabase",
                namespaceName = "",
                columns = new[]
                {
                    new ColumnSchema
                    {
                        fieldName = "id",
                        originalHeader = "id",
                        resolvedType = ResolvedType.Int,
                        attributes = new System.Collections.Generic.Dictionary<string, string>()
                    },
                    new ColumnSchema
                    {
                        fieldName = "name",
                        originalHeader = "name",
                        resolvedType = ResolvedType.String,
                        attributes = new System.Collections.Generic.Dictionary<string, string>()
                    }
                }
            };
        }

        [Test]
        public void TestBasicGeneration()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.serializableClassMode = false;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("public class Item"));
            Assert.IsTrue(code.Contains("public int id"));
            Assert.IsTrue(code.Contains("public string name"));
        }

        [Test]
        public void TestNamespaceWrapping()
        {
            var schema = CreateBasicSchema();
            schema.namespaceName = "MyGame.Data";
            var settings = GetDefaultSettings();
            settings.serializableClassMode = false;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("namespace MyGame.Data"));
            Assert.IsTrue(code.Contains("}\n") || code.Contains("}\r\n"));
        }

        [Test]
        public void TestSerializableClassMode()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.serializableClassMode = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[System.Serializable]"));
            Assert.IsFalse(code.Contains(": ScriptableObject"));
        }

        [Test]
        public void TestListGeneration()
        {
            var schema = CreateBasicSchema();
            schema.columns = new[]
            {
                new ColumnSchema
                {
                    fieldName = "tags",
                    originalHeader = "tags",
                    resolvedType = ResolvedType.IntArray,
                    isList = true,
                    attributes = new System.Collections.Generic.Dictionary<string, string>()
                }
            };
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("List<int>"));
        }

        [Test]
        public void TestArrayGeneration()
        {
            var schema = CreateBasicSchema();
            schema.columns = new[]
            {
                new ColumnSchema
                {
                    fieldName = "values",
                    originalHeader = "values",
                    resolvedType = ResolvedType.IntArray,
                    isList = false,
                    attributes = new System.Collections.Generic.Dictionary<string, string>()
                }
            };
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("int[]"));
        }

        [Test]
        public void TestEnumGeneration()
        {
            var schema = CreateBasicSchema();
            schema.columns = new[]
            {
                new ColumnSchema
                {
                    fieldName = "element",
                    originalHeader = "element",
                    resolvedType = ResolvedType.Enum,
                    enumValues = new[] { "Fire", "Water", "Earth" },
                    attributes = new System.Collections.Generic.Dictionary<string, string>()
                }
            };
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("enum"));
        }

        [Test]
        public void TestRangeAttribute()
        {
            var schema = CreateBasicSchema();
            schema.columns[0].attributes["range"] = "0,100";
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[Range(0f, 100f)]"));
        }

        [Test]
        public void TestTooltipAttribute()
        {
            var schema = CreateBasicSchema();
            schema.columns[0].attributes["tooltip"] = "Item ID";
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[Tooltip(\"Item ID\")]"));
        }

        [Test]
        public void TestSerializeFieldMode()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.useSerializeField = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[SerializeField] private"));
        }

        [Test]
        public void TestCreateAssetMenu()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.generateCreateAssetMenu = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[CreateAssetMenu"));
        }

        [Test]
        public void TestAutoGeneratedHeader()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.addAutoGeneratedHeader = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("Auto-generated"));
        }

        [Test]
        public void TestDatabaseClassGeneration()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateDatabaseClass(schema, settings);

            Assert.IsTrue(code.Contains("public class ItemDatabase"));
            Assert.IsTrue(code.Contains("List<Item>"));
        }
    }
}
