using NUnit.Framework;
using DataToScriptableObject;
using DataToScriptableObject.Editor;
using System.Linq;

namespace DataToScriptableObject.Tests.Editor
{
    public class CodeGeneratorTests
    {
        private GenerationSettings GetDefaultSettings()
        {
            return new GenerationSettings
            {
                SanitizeFieldNames = true,
                NullToken = "null",
                ArrayDelimiter = ";",
                UseListInsteadOfArray = false,
                UseSerializeField = false,
                AddAutoGeneratedHeader = true,
                GenerateCreateAssetMenu = true,
                GenerateTooltips = true,
                ScriptOutputPath = "Assets/Scripts/Generated"
            };
        }

        private TableSchema CreateBasicSchema()
        {
            return new TableSchema
            {
                ClassName = "Item",
                DatabaseName = "ItemDatabase",
                NamespaceName = "",
                Columns = new[]
                {
                    new ColumnSchema
                    {
                        FieldName = "id",
                        OriginalHeader = "id",
                        Type = ResolvedType.Int,
                        Attributes = new System.Collections.Generic.Dictionary<string, string>()
                    },
                    new ColumnSchema
                    {
                        FieldName = "name",
                        OriginalHeader = "name",
                        Type = ResolvedType.String,
                        Attributes = new System.Collections.Generic.Dictionary<string, string>()
                    }
                }
            };
        }

        [Test]
        public void TestBasicGeneration()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.SerializableClassMode = false;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("public class Item"));
            Assert.IsTrue(code.Contains("public int id"));
            Assert.IsTrue(code.Contains("public string name"));
        }

        [Test]
        public void TestNamespaceWrapping()
        {
            var schema = CreateBasicSchema();
            schema.NamespaceName = "MyGame.Data";
            var settings = GetDefaultSettings();
            settings.SerializableClassMode = false;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("namespace MyGame.Data"));
            Assert.IsTrue(code.Contains("}\n") || code.Contains("}\r\n"));
        }

        [Test]
        public void TestSerializableClassMode()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.SerializableClassMode = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[System.Serializable]"));
            Assert.IsFalse(code.Contains(": ScriptableObject"));
        }

        [Test]
        public void TestListGeneration()
        {
            var schema = CreateBasicSchema();
            schema.Columns = new[]
            {
                new ColumnSchema
                {
                    FieldName = "tags",
                    OriginalHeader = "tags",
                    Type = ResolvedType.IntArray,
                    IsList = true,
                    Attributes = new System.Collections.Generic.Dictionary<string, string>()
                }
            };
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("List<int>"));
        }

        [Test]
        public void TestArrayGeneration()
        {
            var schema = CreateBasicSchema();
            schema.Columns = new[]
            {
                new ColumnSchema
                {
                    FieldName = "values",
                    OriginalHeader = "values",
                    Type = ResolvedType.IntArray,
                    IsList = false,
                    Attributes = new System.Collections.Generic.Dictionary<string, string>()
                }
            };
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("int[]"));
        }

        [Test]
        public void TestEnumGeneration()
        {
            var schema = CreateBasicSchema();
            schema.Columns = new[]
            {
                new ColumnSchema
                {
                    FieldName = "element",
                    OriginalHeader = "element",
                    Type = ResolvedType.Enum,
                    EnumValues = new[] { "Fire", "Water", "Earth" },
                    Attributes = new System.Collections.Generic.Dictionary<string, string>()
                }
            };
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("enum"));
        }

        [Test]
        public void TestRangeAttribute()
        {
            var schema = CreateBasicSchema();
            schema.Columns[0].Attributes["range"] = "0,100";
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[Range(0f, 100f)]"));
        }

        [Test]
        public void TestTooltipAttribute()
        {
            var schema = CreateBasicSchema();
            schema.Columns[0].Attributes["tooltip"] = "Item ID";
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[Tooltip(\"Item ID\")]"));
        }

        [Test]
        public void TestSerializeFieldMode()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.UseSerializeField = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[SerializeField] private"));
        }

        [Test]
        public void TestCreateAssetMenu()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.GenerateCreateAssetMenu = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("[CreateAssetMenu"));
        }

        [Test]
        public void TestAutoGeneratedHeader()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();
            settings.AddAutoGeneratedHeader = true;

            string code = CodeGenerator.GenerateScriptableObject(schema, settings);

            Assert.IsTrue(code.Contains("Auto-generated"));
        }

        [Test]
        public void TestDatabaseClassGeneration()
        {
            var schema = CreateBasicSchema();
            var settings = GetDefaultSettings();

            string code = CodeGenerator.GenerateDatabaseClass(schema, settings);

            Assert.IsTrue(code.Contains("public class ItemDatabase"));
            Assert.IsTrue(code.Contains("List<Item>"));
        }
    }
}
