using System.Linq;
using System.Text.RegularExpressions;
using DataToScriptableObject;
using DataToScriptableObject.Editor;
using NUnit.Framework;

namespace DataToScriptableObject.Tests.Editor
{
    /// <summary>
    /// Comprehensive end-to-end tests for the complete pipeline:
    /// CSV → RawTableData → TableSchema → C# Code → ScriptableObject → Database
    /// 
    /// These tests ensure the entire system works correctly for real-world scenarios
    /// when users create ScriptableObject databases.
    /// </summary>
    public class FullPipelineTests
    {
        private GenerationSettings GetDefaultSettings()
        {
            return new GenerationSettings
            {
                SanitizeFieldNames = true,
                NullToken = "null",
                ArrayDelimiter = ";",
                UseListInsteadOfArray = false,
                UseSerializeField = false,
                GenerateCreateAssetMenu = true,
                AddAutoGeneratedHeader = true,
                GenerateTooltips = true,
                ScriptOutputPath = "Assets/Scripts/Generated"
            };
        }

        #region Complex Type Conversion Pipeline

        [Test]
        public void TestPipeline_AllBasicTypes()
        {
            // Test all basic types through entire pipeline
            string csv = @"id,name,health,speed,isDead,description
int,string,float,double,bool,string
1,Hero,100.5,5.25,false,""A brave hero""";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify types made it through
            Assert.IsTrue(code.Contains("public int id"), "int type should be in generated code");
            Assert.IsTrue(code.Contains("public string name"), "string type should be in generated code");
            Assert.IsTrue(code.Contains("public float health"), "float type should be in generated code");
            Assert.IsTrue(code.Contains("public double speed"), "double type should be in generated code");
            Assert.IsTrue(code.Contains("public bool isDead"), "bool type should be in generated code");
            
            // Verify class structure
            Assert.IsTrue(code.Contains("class GeneratedEntry"), "Entry class should be generated");
            Assert.IsTrue(code.Contains(": ScriptableObject"), "Should inherit from ScriptableObject");
        }

        [Test]
        public void TestPipeline_ArrayTypes()
        {
            // Test array types through pipeline
            string csv = @"id,tags,scores,flags
int,string[],float[],bool[]
1,""tag1;tag2;tag3"",""1.5;2.5;3.5"",""true;false;true""";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify array types in code
            Assert.IsTrue(code.Contains("public string[] tags"), "string array should be generated");
            Assert.IsTrue(code.Contains("public float[] scores"), "float array should be generated");
            Assert.IsTrue(code.Contains("public bool[] flags"), "bool array should be generated");
        }

        [Test]
        public void TestPipeline_UnityTypes()
        {
            // Test Unity-specific types
            string csv = @"id,position,size,color,icon,model
int,vector3,vector2,color,sprite,prefab
1,""1.0;2.0;3.0"",""10.0;20.0"",""1.0;0.5;0.0;1.0"",icon.png,model.prefab";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify Unity types
            Assert.IsTrue(code.Contains("public Vector3 position"), "Vector3 should be generated");
            Assert.IsTrue(code.Contains("public Vector2 size"), "Vector2 should be generated");
            Assert.IsTrue(code.Contains("public Color color"), "Color should be generated");
            Assert.IsTrue(code.Contains("public Sprite icon"), "Sprite should be generated");
            Assert.IsTrue(code.Contains("public GameObject model"), "GameObject should be generated for prefab");
            
            // Verify Unity namespace
            Assert.IsTrue(code.Contains("using UnityEngine;"), "Should include UnityEngine namespace");
        }

        [Test]
        public void TestPipeline_EnumGeneration()
        {
            // Test enum generation through pipeline
            string csv = @"id,element,rarity
int,enum,enum
,Fire,Water,Earth,Common,Rare,Epic,Legendary
1,Fire,Rare";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify enum declarations come before class
            int elementEnumPos = code.IndexOf("public enum Element");
            int rarityEnumPos = code.IndexOf("public enum Rarity");
            int classPos = code.IndexOf("public class GeneratedEntry");
            
            Assert.Greater(elementEnumPos, -1, "Element enum should be declared");
            Assert.Greater(rarityEnumPos, -1, "Rarity enum should be declared");
            Assert.Greater(classPos, -1, "Class should be declared");
            Assert.Less(elementEnumPos, classPos, "Element enum should come before class");
            Assert.Less(rarityEnumPos, classPos, "Rarity enum should come before class");
            
            // Verify enum values
            Assert.IsTrue(code.Contains("Fire"), "Fire enum value should exist");
            Assert.IsTrue(code.Contains("Water"), "Water enum value should exist");
            Assert.IsTrue(code.Contains("Common"), "Common enum value should exist");
            Assert.IsTrue(code.Contains("Legendary"), "Legendary enum value should exist");
            
            // Verify enum fields in class
            Assert.IsTrue(code.Contains("public Element element"), "Element field should use enum type");
            Assert.IsTrue(code.Contains("public Rarity rarity"), "Rarity field should use enum type");
        }

        [Test]
        public void TestPipeline_TypeInferenceWhenNoHints()
        {
            // Test type inference when no explicit type hints
            string csv = @"id,name,damage,isActive
1,Sword,15.5,true
2,Shield,0,false";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Type inference should detect types from data
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type, "Should infer int from data");
            Assert.AreEqual(ResolvedType.String, schema.Columns[1].Type, "Should infer string from data");
            Assert.AreEqual(ResolvedType.Float, schema.Columns[2].Type, "Should infer float from decimal data");
            Assert.AreEqual(ResolvedType.Bool, schema.Columns[3].Type, "Should infer bool from true/false");
        }

        #endregion

        #region Directive and Naming Pipeline

        [Test]
        public void TestPipeline_DirectivesAffectCodeStructure()
        {
            // Test that directives properly affect generated code structure
            string csv = @"#class:WeaponData
#database:WeaponDatabase
#namespace:MyGame.Combat.Weapons
id,name
int,string
1,Sword";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify directives are applied
            Assert.AreEqual("WeaponData", schema.ClassName);
            Assert.AreEqual("WeaponDatabase", schema.DatabaseName);
            Assert.AreEqual("MyGame.Combat.Weapons", schema.NamespaceName);
            
            // Verify in generated code
            Assert.IsTrue(code.Contains("namespace MyGame.Combat.Weapons"), "Namespace should be in code");
            Assert.IsTrue(code.Contains("public class WeaponData"), "Class name should be in code");
            Assert.IsTrue(code.Contains("public class WeaponDatabase"), "Database class should be in code");
        }

        [Test]
        public void TestPipeline_FieldNameSanitization()
        {
            // Test that field names are properly sanitized through pipeline
            string csv = @"player-id,player name,health_points,is dead?,damage%,special.bonus
1,Hero,100,false,25,10";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Field names should be sanitized to valid C# identifiers
            Assert.IsTrue(code.Contains("public int playerId") || code.Contains("public string playerId"), 
                "player-id should be sanitized to playerId");
            Assert.IsTrue(code.Contains("public string playerName"), 
                "player name should be sanitized to playerName");
            Assert.IsTrue(code.Contains("public float healthPoints") || code.Contains("public int healthPoints"), 
                "health_points should be sanitized to healthPoints");
            Assert.IsTrue(code.Contains("public bool isDead"), 
                "is dead? should be sanitized to isDead");
            Assert.IsTrue(code.Contains("damage"), 
                "damage% should have % removed");
        }

        [Test]
        public void TestPipeline_DuplicateHeaderHandling()
        {
            // Test handling of duplicate headers through pipeline
            string csv = @"id,name,name,value,value
1,Item1,Item1_Alt,10,20";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Should handle duplicates by making them unique
            Assert.AreEqual(5, schema.Columns.Length, "Should have 5 columns");
            
            // Generated code should have unique field names
            int nameCount = Regex.Matches(code, @"public \w+ name").Count;
            Assert.Greater(nameCount, 0, "Should have at least one 'name' field");
        }

        [Test]
        public void TestPipeline_EmptyHeaderHandling()
        {
            // Test handling of empty headers
            string csv = @",name,,value
1,Item,data,10";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Should generate valid field names for empty headers
            Assert.AreEqual(4, schema.Columns.Length);
            Assert.IsTrue(code.Contains("public"), "Should have generated fields");
        }

        [Test]
        public void TestPipeline_SpecialCharactersInClassNames()
        {
            // Test special characters in directives get sanitized
            string csv = @"#class:My-Special_Class@123
#namespace:My.Name$pace!
id
1";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Class name should be sanitized but preserve intent
            Assert.IsTrue(schema.ClassName.Contains("My"));
            Assert.IsTrue(schema.ClassName.Contains("Special"));
            Assert.IsTrue(schema.ClassName.Contains("Class"));
            
            // Generated code should have valid C# identifiers
            Assert.IsTrue(code.Contains("public class"), "Should have class declaration");
            Assert.IsFalse(code.Contains("@"), "Should not have @ in code");
            Assert.IsFalse(code.Contains("$"), "Should not have $ in code (outside string literals)");
        }

        #endregion

        #region Attributes and Metadata Pipeline

        [Test]
        public void TestPipeline_RangeAttributes()
        {
            // Test Range attributes flow through pipeline
            string csv = @"id,health,damage,speed
int,int,float,float
,range(0;100),range(1;50),range(0.0;10.0)
1,75,25,5.5";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify Range attributes in generated code
            Assert.IsTrue(code.Contains("[Range(0f, 100f)]"), "health should have Range(0f, 100f)");
            Assert.IsTrue(code.Contains("[Range(1f, 50f)]"), "damage should have Range(1f, 50f)");
            Assert.IsTrue(code.Contains("[Range(0.0f, 10.0f)]"), "speed should have Range(0.0f, 10.0f)");
        }

        [Test]
        public void TestPipeline_TooltipAttributes()
        {
            // Test Tooltip attributes are generated
            string csv = @"id,name,damage
int,string,int
key,name,
1,Sword,15";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var settings = GetDefaultSettings();
            settings.GenerateTooltips = true;
            
            var schema = SchemaBuilder.Build(rawData, settings);
            var code = CodeGenerator.GenerateScriptableObject(schema, settings);
            
            // Should generate tooltips for key/name columns
            if (settings.GenerateTooltips)
            {
                Assert.IsTrue(code.Contains("[Tooltip("), "Should have Tooltip attributes");
            }
        }

        [Test]
        public void TestPipeline_MultilineAttributes()
        {
            // Test Multiline attributes for string fields
            string csv = @"id,description
int,string
,multiline(5)
1,""A long description that spans multiple lines""";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify Multiline attribute
            Assert.IsTrue(code.Contains("[Multiline(5)]") || code.Contains("[TextArea"), 
                "Should have multiline attribute");
        }

        [Test]
        public void TestPipeline_KeyAndNameFlags()
        {
            // Test key and name flags affect generated code
            string csv = @"id,title,value
int,string,float
key,name,
1,Important Item,100.5";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify flags were recognized
            Assert.IsTrue(schema.Columns[0].IsKey, "id should be marked as key");
            Assert.IsTrue(schema.Columns[1].IsName, "title should be marked as name");
            
            // Key and name fields might have special treatment in database code
            Assert.IsTrue(code.Contains("public int id"), "Key field should be in code");
            Assert.IsTrue(code.Contains("public string title"), "Name field should be in code");
        }

        #endregion

        #region Database Generation Pipeline

        [Test]
        public void TestPipeline_DatabaseClassGeneration()
        {
            // Test that database class is properly generated
            string csv = @"#class:Item
#database:ItemDatabase
id,name
1,Sword
2,Shield";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Should contain both entry and database classes
            Assert.IsTrue(code.Contains("public class Item"), "Entry class should be generated");
            Assert.IsTrue(code.Contains("public class ItemDatabase"), "Database class should be generated");
            Assert.IsTrue(code.Contains("List<Item>") || code.Contains("Item[]"), 
                "Database should contain collection of entries");
        }

        [Test]
        public void TestPipeline_DatabaseWithLookupMethods()
        {
            // Test database with key field generates lookup methods
            string csv = @"id,name,value
int,string,float
key,name,
1,Item1,10.5
2,Item2,20.5";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Database should have lookup methods
            Assert.IsTrue(schema.Columns[0].IsKey, "Should have key column");
            
            // Generated database might have GetById, GetByName, etc.
            // This depends on CodeGenerator implementation
        }

        [Test]
        public void TestPipeline_CreateAssetMenuAttribute()
        {
            // Test CreateAssetMenu attribute is generated
            string csv = @"#class:Weapon
id,name
1,Sword";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var settings = GetDefaultSettings();
            settings.GenerateCreateAssetMenu = true;
            
            var schema = SchemaBuilder.Build(rawData, settings);
            var code = CodeGenerator.GenerateScriptableObject(schema, settings);
            
            if (settings.GenerateCreateAssetMenu)
            {
                Assert.IsTrue(code.Contains("[CreateAssetMenu("), 
                    "Should have CreateAssetMenu attribute");
                Assert.IsTrue(code.Contains("Weapon"), 
                    "CreateAssetMenu should reference class name");
            }
        }

        #endregion

        #region Complex Real-World Scenarios

        [Test]
        public void TestPipeline_CompleteWeaponSystem()
        {
            // Complete weapon system with all features
            string csv = @"#class:Weapon
#database:WeaponDatabase
#namespace:Game.Items.Weapons
id,name,damage,attackSpeed,range,rarity,elementType,abilities
int,string,float,float,float,enum,enum,string[]
key,name,range(0;200),range(0.1;5.0),range(0.5;10.0),Common,Rare,Epic,Legendary,None,Fire,Ice,Lightning,poison,stun,lifesteal
1,Excalibur,150.0,1.2,2.5,Legendary,Fire,""lifesteal;stun""
2,Iron Dagger,25.0,2.5,1.0,Common,None,""poison""
3,Frost Staff,80.0,0.8,5.0,Epic,Ice,""stun;lifesteal""";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            Assert.AreEqual(3, rawData.Directives.Length, "Should have 3 directives");
            Assert.IsNotNull(rawData.TypeHints, "Should have type hints row");
            Assert.IsNotNull(rawData.Flags, "Should have flags row");
            Assert.AreEqual(3, rawData.DataRows.Length, "Should have 3 data rows");
            
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            Assert.AreEqual("Weapon", schema.ClassName);
            Assert.AreEqual("WeaponDatabase", schema.DatabaseName);
            Assert.AreEqual("Game.Items.Weapons", schema.NamespaceName);
            Assert.AreEqual(8, schema.Columns.Length);
            
            // Verify specific column types
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type);
            Assert.AreEqual(ResolvedType.String, schema.Columns[1].Type);
            Assert.AreEqual(ResolvedType.Float, schema.Columns[2].Type);
            Assert.AreEqual(ResolvedType.Enum, schema.Columns[5].Type);
            Assert.AreEqual(ResolvedType.Enum, schema.Columns[6].Type);
            Assert.AreEqual(ResolvedType.StringArray, schema.Columns[7].Type);
            
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify generated code structure
            Assert.IsTrue(code.Contains("namespace Game.Items.Weapons"));
            Assert.IsTrue(code.Contains("public class Weapon"));
            Assert.IsTrue(code.Contains("public class WeaponDatabase"));
            
            // Verify enum declarations
            Assert.IsTrue(code.Contains("public enum Rarity"));
            Assert.IsTrue(code.Contains("Common"));
            Assert.IsTrue(code.Contains("Legendary"));
            Assert.IsTrue(code.Contains("public enum ElementType"));
            Assert.IsTrue(code.Contains("Fire"));
            Assert.IsTrue(code.Contains("Lightning"));
            
            // Verify fields
            Assert.IsTrue(code.Contains("public int id"));
            Assert.IsTrue(code.Contains("public string name"));
            Assert.IsTrue(code.Contains("public float damage"));
            Assert.IsTrue(code.Contains("public Rarity rarity"));
            Assert.IsTrue(code.Contains("public ElementType elementType"));
            Assert.IsTrue(code.Contains("public string[] abilities"));
            
            // Verify Range attributes
            Assert.IsTrue(code.Contains("[Range(0f, 200f)]"));
            Assert.IsTrue(code.Contains("[Range(0.1f, 5.0f)]"));
        }

        [Test]
        public void TestPipeline_LocalizationSystem()
        {
            // Localization database with multiple languages
            string csv = @"#class:LocalizedText
#database:LocalizationDatabase
key,en,es,fr,ja
string,string,string,string,string
key,,,,,
UI_HELLO,Hello,Hola,Bonjour,こんにちは
UI_GOODBYE,Goodbye,Adiós,Au revoir,さようなら";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify all language fields are generated
            Assert.IsTrue(code.Contains("public string key"));
            Assert.IsTrue(code.Contains("public string en"));
            Assert.IsTrue(code.Contains("public string es"));
            Assert.IsTrue(code.Contains("public string fr"));
            Assert.IsTrue(code.Contains("public string ja"));
            
            // Key field should be marked
            Assert.IsTrue(schema.Columns[0].IsKey);
        }

        [Test]
        public void TestPipeline_SkillTreeSystem()
        {
            // Skill tree with prerequisites and complex relationships
            string csv = @"#class:Skill
#database:SkillDatabase
id,name,description,levelRequired,manaCost,cooldown,prerequisites
int,string,string,int,int,float,string[]
key,name,multiline(3),,,,
1,Fireball,""Launch a fiery projectile"",1,20,3.0,
2,Greater Fireball,""Enhanced fireball"",5,35,5.0,""Fireball""
3,Meteor,""Rain fire from sky"",15,80,20.0,""Fireball;Greater Fireball""";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify multiline attribute on description
            Assert.IsTrue(code.Contains("[Multiline(3)]") || code.Contains("[TextArea"));
            
            // Verify array for prerequisites
            Assert.IsTrue(code.Contains("public string[] prerequisites"));
            
            // Verify key and name
            Assert.IsTrue(schema.Columns[0].IsKey);
            Assert.IsTrue(schema.Columns[1].IsName);
        }

        [Test]
        public void TestPipeline_InventoryWithUnityAssets()
        {
            // Inventory system with Unity asset references
            string csv = @"#class:InventoryItem
id,name,icon,prefab,value,stackable
int,string,sprite,prefab,int,bool
1,Health Potion,potion_icon.png,potion.prefab,50,true
2,Magic Sword,sword_icon.png,sword.prefab,1000,false";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify Unity asset types
            Assert.AreEqual(ResolvedType.Sprite, schema.Columns[2].Type);
            Assert.AreEqual(ResolvedType.Prefab, schema.Columns[3].Type);
            
            Assert.IsTrue(code.Contains("public Sprite icon"));
            Assert.IsTrue(code.Contains("public GameObject prefab"));
            Assert.IsTrue(code.Contains("using UnityEngine"));
        }

        [Test]
        public void TestPipeline_QuestSystemWithComplexData()
        {
            // Quest system with objectives, rewards, and requirements
            string csv = @"id,title,description,objectives,rewards,requirements
int,string,string,string[],string[],string[]
1,""The Lost Sword"",""Find the legendary sword"",""Search ruins;Defeat guardian;Retrieve sword"",""1000 gold;Legendary weapon"",""Level 10""
2,""Village Defense"",""Defend against goblins"",""Kill 10 goblins;Protect mayor"",""500 gold;Experience"",""Level 5""";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Verify array types for lists
            Assert.AreEqual(ResolvedType.StringArray, schema.Columns[3].Type); // objectives
            Assert.AreEqual(ResolvedType.StringArray, schema.Columns[4].Type); // rewards
            Assert.AreEqual(ResolvedType.StringArray, schema.Columns[5].Type); // requirements
            
            Assert.IsTrue(code.Contains("public string[] objectives"));
            Assert.IsTrue(code.Contains("public string[] rewards"));
            Assert.IsTrue(code.Contains("public string[] requirements"));
        }

        #endregion

        #region Edge Cases and Error Handling

        [Test]
        public void TestPipeline_EmptyEnumHandling()
        {
            // Test handling of enum column with no values
            string csv = @"id,type
int,enum
,
1,Unknown";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            // Should handle gracefully - might fallback to string or create empty enum
            Assert.AreEqual(2, schema.Columns.Length);
        }

        [Test]
        public void TestPipeline_AllNullData()
        {
            // Test with all null values
            string csv = @"id,name,value
int,string,float
null,null,null";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Should still generate valid code
            Assert.IsTrue(code.Contains("public class"));
        }

        [Test]
        public void TestPipeline_ExtremelyLongFieldNames()
        {
            // Test very long field names get handled
            string longName = new string('a', 100);
            string csv = $"id,{longName}\n1,value";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Should handle long names (might truncate or sanitize)
            Assert.IsTrue(code.Contains("public"));
        }

        [Test]
        public void TestPipeline_OnlyHeadersNoData()
        {
            // Test with headers but no data rows
            string csv = @"id,name,value
int,string,float";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Should still generate valid code structure
            Assert.IsTrue(code.Contains("public int id"));
            Assert.IsTrue(code.Contains("public string name"));
            Assert.IsTrue(code.Contains("public float value"));
        }

        [Test]
        public void TestPipeline_InvalidTypeHintsFallbackToInference()
        {
            // Test that invalid type hints fall back to inference
            string csv = @"id,name,value
invalidType,unknownType,badType
1,Item,15.5";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            // Should fall back to type inference from data
            Assert.AreEqual(3, schema.Columns.Length);
            // Types should be inferred from actual data
        }

        #endregion

        #region Code Quality Validation

        [Test]
        public void TestPipeline_GeneratedCodeHasNoSyntaxErrors()
        {
            // Verify generated code looks syntactically correct
            string csv = @"#class:TestItem
#namespace:Test
id,name,value,active
int,string,float,bool
1,Item1,10.5,true";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Basic syntax checks
            Assert.IsTrue(code.Contains("namespace Test"), "Should have namespace");
            Assert.IsTrue(code.Contains("{"), "Should have opening braces");
            Assert.IsTrue(code.Contains("}"), "Should have closing braces");
            
            // Count braces should be balanced
            int openBraces = code.Count(c => c == '{');
            int closeBraces = code.Count(c => c == '}');
            Assert.AreEqual(openBraces, closeBraces, "Braces should be balanced");
            
            // Should have proper class structure
            Assert.IsTrue(code.Contains("public class TestItem"));
            Assert.IsTrue(code.Contains(": ScriptableObject"));
            
            // Should not have obvious errors
            Assert.IsFalse(code.Contains("ERROR"), "Should not contain ERROR text");
            Assert.IsFalse(code.Contains("INVALID"), "Should not contain INVALID text");
        }

        [Test]
        public void TestPipeline_GeneratedCodeHasRequiredUsings()
        {
            // Verify all necessary using statements are included
            string csv = @"id,position,color,icon
int,vector3,color,sprite
1,""1;2;3"",""1;0;0;1"",icon.png";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Should have Unity usings for Unity types
            Assert.IsTrue(code.Contains("using UnityEngine;"), "Should have UnityEngine for Vector3, Color, Sprite");
            Assert.IsTrue(code.Contains("using System.Collections.Generic;") || 
                         code.Contains("using System.Collections;"), 
                         "Should have Collections for List/Array");
        }

        [Test]
        public void TestPipeline_DatabaseClassHasProperStructure()
        {
            // Verify database class has proper structure
            string csv = @"#database:MyDatabase
id,name
1,Item";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            var code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            
            // Database should inherit from ScriptableObject
            Assert.IsTrue(code.Contains("class MyDatabase"), "Should have database class");
            Assert.IsTrue(code.Contains(": ScriptableObject"), "Database should inherit ScriptableObject");
            
            // Database should have entries collection
            Assert.IsTrue(code.Contains("List<") || code.Contains("[]"), 
                "Database should have collection of entries");
        }

        #endregion
    }
}
