using NUnit.Framework;
using DataToScriptableObject;
using DataToScriptableObject.Editor;
using System.Linq;

namespace DataToScriptableObject.Tests.Editor
{
    /// <summary>
    /// Integration tests that verify the full pipeline from CSV parsing through schema building to code generation.
    /// These tests help diagnose issues that span multiple components.
    /// </summary>
    public class IntegrationTests
    {
        private GenerationSettings GetDefaultSettings()
        {
            return new GenerationSettings
            {
                SanitizeFieldNames = true,
                NullToken = "null",
                ArrayDelimiter = ";",
                UseListInsteadOfArray = false,
                UseSerializeField = false,
                GenerateCreateAssetMenu = true,
                AddAutoGeneratedHeader = true,
                GenerateTooltips = true,
                ScriptOutputPath = "Assets/Scripts/Generated"
            };
        }

        #region Full Pipeline Tests

        [Test]
        public void TestFullPipelineBasicCSV()
        {
            // Full pipeline: CSV -> RawTableData -> TableSchema -> Code
            string csv = "id,name,damage\n1,Sword,15";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            Assert.AreEqual(3, rawData.Headers.Length, "Step 1: CSV should parse to 3 headers");
            
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            Assert.AreEqual(3, schema.Columns.Length, "Step 2: Schema should have 3 columns");
            
            string code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            Assert.IsTrue(code.Contains("public class"), "Step 3: Code should contain class definition");
        }

        [Test]
        public void TestFullPipelineWithDirectives()
        {
            string csv = "#class:Weapon\n#namespace:Game.Items\nid,name\n1,Sword";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            Assert.AreEqual(2, rawData.Directives.Length, "Should have 2 directives");
            
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            Assert.AreEqual("Weapon", schema.ClassName, "Class name should be from directive");
            Assert.AreEqual("Game.Items", schema.NamespaceName, "Namespace should be from directive");
            
            string code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            Assert.IsTrue(code.Contains("namespace Game.Items"), "Code should have namespace");
            Assert.IsTrue(code.Contains("public class Weapon"), "Code should have correct class name");
        }

        [Test]
        public void TestFullPipelineThreeRowHeader()
        {
            string csv = "id,name,damage\nint,string,float\nkey,name,range(0;100)\n1,Sword,15.5";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            Assert.AreEqual(3, rawData.Headers.Length, "Should parse headers");
            Assert.IsNotNull(rawData.TypeHints, "Should have type hints");
            Assert.IsNotNull(rawData.Flags, "Should have flags");
            
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type);
            Assert.AreEqual(ResolvedType.String, schema.Columns[1].Type);
            Assert.AreEqual(ResolvedType.Float, schema.Columns[2].Type);
            Assert.IsTrue(schema.Columns[0].IsKey);
            Assert.IsTrue(schema.Columns[1].IsName);
            
            string code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            Assert.IsTrue(code.Contains("public int id"));
            Assert.IsTrue(code.Contains("public string name"));
            Assert.IsTrue(code.Contains("public float damage"));
            Assert.IsTrue(code.Contains("[Range(0f, 100f)]"));
        }

        [Test]
        public void TestFullPipelineWithEnum()
        {
            string csv = "id,element\nint,enum\n,Fire,Water,Earth\n1,Fire";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.Enum, schema.Columns[1].Type);
            Assert.IsNotNull(schema.Columns[1].EnumValues);
            
            string code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            Assert.IsTrue(code.Contains("enum"), "Generated code should contain enum");
        }

        #endregion

        #region Type Inference Pipeline Tests

        [Test]
        public void TestPipelineTypeInference()
        {
            // Verify type inference works through the full pipeline
            string csv = "intCol,floatCol,boolCol,stringCol\n42,3.14,true,text";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type, "Should infer int");
            Assert.AreEqual(ResolvedType.Float, schema.Columns[1].Type, "Should infer float");
            Assert.AreEqual(ResolvedType.Bool, schema.Columns[2].Type, "Should infer bool");
            Assert.AreEqual(ResolvedType.String, schema.Columns[3].Type, "Should infer string");
        }

        [Test]
        public void TestPipelineTypeInferenceMultipleRows()
        {
            // Type inference with multiple data rows
            string csv = "a,b,c\n1,1.5,true\n2,2.5,false\n3,3.5,yes";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type, "All ints should infer as int");
            Assert.AreEqual(ResolvedType.Float, schema.Columns[1].Type, "All floats should infer as float");
            Assert.AreEqual(ResolvedType.Bool, schema.Columns[2].Type, "true/false/yes should infer as bool");
        }

        [Test]
        public void TestPipelineTypeOverridesByHint()
        {
            // Type hints should override inference
            string csv = "id\nstring\n42";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.String, schema.Columns[0].Type, "Type hint should override inference");
        }

        #endregion

        #region Edge Case Integration Tests

        [Test]
        public void TestPipelineEmptyCSV()
        {
            string csv = "";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(0, schema.Columns.Length);
            Assert.AreEqual(0, schema.Rows.Count);
        }

        [Test]
        public void TestPipelineOnlyHeaders()
        {
            string csv = "a,b,c";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.Columns.Length);
            Assert.AreEqual(0, schema.Rows.Count);
            
            // Should still generate valid code
            string code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            Assert.IsTrue(code.Contains("public class"));
        }

        [Test]
        public void TestPipelineSpecialCharactersInHeaders()
        {
            string csv = "player-id,max_health,Display Name\n1,100,Hero";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            // Headers should be sanitized for code generation
            Assert.AreEqual("playerId", schema.Columns[0].FieldName);
            Assert.AreEqual("maxHealth", schema.Columns[1].FieldName);
            Assert.AreEqual("displayName", schema.Columns[2].FieldName);
            
            // Original headers should be preserved
            Assert.AreEqual("player-id", schema.Columns[0].OriginalHeader);
            Assert.AreEqual("max_health", schema.Columns[1].OriginalHeader);
            Assert.AreEqual("Display Name", schema.Columns[2].OriginalHeader);
        }

        [Test]
        public void TestPipelineDuplicateHeaders()
        {
            string csv = "name,value,name\n1,2,3";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            // All columns should be present
            Assert.AreEqual(3, schema.Columns.Length);
            
            // Should have warnings about duplicates
            Assert.IsTrue(schema.Warnings.Any(w => w.message.Contains("Duplicate")));
        }

        [Test]
        public void TestPipelineQuotedFields()
        {
            string csv = "name,description\nItem,\"A really, really long description\"";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            
            Assert.AreEqual(1, rawData.DataRows.Length);
            Assert.AreEqual("A really, really long description", rawData.DataRows[0][1]);
        }

        [Test]
        public void TestPipelineArrayFields()
        {
            string csv = "name,tags\nstring,string[]\nItem,a;b;c";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.String, schema.Columns[0].Type);
            Assert.AreEqual(ResolvedType.StringArray, schema.Columns[1].Type);
            
            string code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            Assert.IsTrue(code.Contains("string[]") || code.Contains("List<string>"));
        }

        #endregion

        #region Database Generation Pipeline Tests

        [Test]
        public void TestDatabaseGeneration()
        {
            string csv = "#class:Item\n#database:ItemDatabase\nid,name\n1,Sword";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            string entryCode = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            string dbCode = CodeGenerator.GenerateDatabaseClass(schema, GetDefaultSettings());
            
            Assert.IsTrue(entryCode.Contains("public class Item"));
            Assert.IsTrue(dbCode.Contains("public class ItemDatabase"));
            Assert.IsTrue(dbCode.Contains("List<Item>"));
        }

        [Test]
        public void TestSerializableClassMode()
        {
            string csv = "id,name\n1,Item";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            var settings = GetDefaultSettings();
            settings.SerializableClassMode = true;
            
            string code = CodeGenerator.GenerateScriptableObject(schema, settings);
            
            Assert.IsTrue(code.Contains("[System.Serializable]"));
            Assert.IsFalse(code.Contains(": ScriptableObject"));
        }

        #endregion

        #region CSV Format Variations

        [Test]
        public void TestPipelineSemicolonDelimiter()
        {
            string csv = "a;b;c\n1;2;3";
            
            var rawData = CSVReader.Parse(csv, ";", "#", 1);
            
            Assert.AreEqual(3, rawData.Headers.Length);
            Assert.AreEqual("a", rawData.Headers[0]);
        }

        [Test]
        public void TestPipelineTabDelimiter()
        {
            string csv = "a\tb\tc\n1\t2\t3";
            
            var rawData = CSVReader.Parse(csv, "\t", "#", 1);
            
            Assert.AreEqual(3, rawData.Headers.Length);
        }

        [Test]
        public void TestPipelineAutoDelimiter()
        {
            string csv = "a;b;c\n1;2;3";
            
            var rawData = CSVReader.Parse(csv, "auto", "#", 1);
            
            Assert.AreEqual(3, rawData.Headers.Length);
        }

        [Test]
        public void TestPipelineWindowsLineEndings()
        {
            string csv = "a,b\r\n1,2\r\n3,4";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            
            Assert.AreEqual(2, rawData.DataRows.Length);
        }

        [Test]
        public void TestPipelineMacLineEndings()
        {
            string csv = "a,b\r1,2\r3,4";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            
            Assert.AreEqual(2, rawData.DataRows.Length);
        }

        [Test]
        public void TestPipelineWithBOM()
        {
            string csv = "\uFEFFa,b,c\n1,2,3";
            
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            
            Assert.AreEqual("a", rawData.Headers[0], "BOM should be stripped");
        }

        #endregion

        #region Complex Real-World Scenarios

        [Test]
        public void TestRealWorldItemTable()
        {
            string csv = "#class:GameItem\n" +
                "#namespace:Game.Data\n" +
                "id,name,description,price,stackable,category\n" +
                "int,string,string,float,bool,enum\n" +
                "key,name,tooltip(Item description),,optional,Common,Uncommon,Rare,Epic,Legendary\n" +
                "1,Health Potion,Restores 50 HP,10.5,true,Common\n" +
                "2,Sword of Fire,A flaming sword,100.0,false,Rare\n" +
                "3,Magic Staff,Powerful magic weapon,250.0,false,Epic";

            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual("GameItem", schema.ClassName);
            Assert.AreEqual("Game.Data", schema.NamespaceName);
            Assert.AreEqual(6, schema.Columns.Length);
            Assert.IsTrue(schema.Columns[0].IsKey);
            Assert.IsTrue(schema.Columns[1].IsName);
            Assert.AreEqual(ResolvedType.Enum, schema.Columns[5].Type);
            
            string code = CodeGenerator.GenerateScriptableObject(schema, GetDefaultSettings());
            Assert.IsTrue(code.Contains("namespace Game.Data"));
            Assert.IsTrue(code.Contains("public class GameItem"));
        }

        [Test]
        public void TestRealWorldCharacterStats()
        {
            string csv = "id,class,hp,attack,defense,speed\n" +
                "int,enum,int,int,int,int\n" +
                "key,Warrior,Mage,Rogue,,,\n" +
                "1,Warrior,100,15,10,5\n" +
                "2,Mage,60,20,5,8\n" +
                "3,Rogue,80,12,7,15";

            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(6, schema.Columns.Length);
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type);
            Assert.AreEqual(ResolvedType.Enum, schema.Columns[1].Type);
            Assert.AreEqual(3, schema.Rows.Count);
        }

        #endregion
    }
}
