using NUnit.Framework;
using DataToScriptableObject;
using DataToScriptableObject.Editor;
using System.Linq;

namespace DataToScriptableObject.Tests.Editor
{
    public class SchemaBuilderTests
    {
        private GenerationSettings GetDefaultSettings()
        {
            return new GenerationSettings
            {
                SanitizeFieldNames = true,
                NullToken = "null",
                ArrayDelimiter = ";",
                UseListInsteadOfArray = false,
                UseSerializeField = false,
                GenerateCreateAssetMenu = true,
                AddAutoGeneratedHeader = true
            };
        }

        [Test]
        public void TestBasicThreeRowHeader()
        {
            string csv = "id,name,damage\nint,string,float\nkey,name,\n1,Sword,15.5";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.Columns.Length);
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type);
            Assert.AreEqual(ResolvedType.String, schema.Columns[1].Type);
            Assert.AreEqual(ResolvedType.Float, schema.Columns[2].Type);
            Assert.IsTrue(schema.Columns[0].IsKey);
            Assert.IsTrue(schema.Columns[1].IsName);
        }

        [Test]
        public void TestSingleRowHeader()
        {
            string csv = "id,name,value\n1,Item,100";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.Columns.Length);
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type);
            Assert.AreEqual(ResolvedType.String, schema.Columns[1].Type);
            Assert.AreEqual(ResolvedType.Int, schema.Columns[2].Type);
        }

        [Test]
        public void TestTwoRowHeader()
        {
            string csv = "id,name,value\nint,string,float\n1,Item,10.5";
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.Columns.Length);
            Assert.AreEqual(ResolvedType.Int, schema.Columns[0].Type);
            Assert.AreEqual(ResolvedType.String, schema.Columns[1].Type);
            Assert.AreEqual(ResolvedType.Float, schema.Columns[2].Type);
        }

        [Test]
        public void TestEnumParsing()
        {
            string csv = "id,element\nint,enum\n,Fire,Water,Earth\n1,Fire";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.Enum, schema.Columns[1].Type);
            Assert.IsNotNull(schema.Columns[1].EnumValues);
            Assert.AreEqual(3, schema.Columns[1].EnumValues.Length);
            Assert.Contains("Fire", schema.Columns[1].EnumValues);
            Assert.Contains("Water", schema.Columns[1].EnumValues);
            Assert.Contains("Earth", schema.Columns[1].EnumValues);
        }

        [Test]
        public void TestRangeParsing()
        {
            string csv = "id,damage\nint,float\n,range(0;100)\n1,50";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.Columns[1].Attributes.ContainsKey("range"));
            Assert.AreEqual("0,100", schema.Columns[1].Attributes["range"]);
        }

        [Test]
        public void TestTooltipParsing()
        {
            string csv = "id,damage\nint,float\n,tooltip(Base damage)\n1,50";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.Columns[1].Attributes.ContainsKey("tooltip"));
            Assert.AreEqual("Base damage", schema.Columns[1].Attributes["tooltip"]);
        }

        [Test]
        public void TestSkipColumn()
        {
            string csv = "id,temp,name\nint,string,string\n,skip,\n1,ignore,Item";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.Columns[1].IsSkipped);
        }

        [Test]
        public void TestKeyAndName()
        {
            string csv = "id,name\nint,string\nkey,name\n1,Item";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.Columns[0].IsKey);
            Assert.IsTrue(schema.Columns[1].IsName);
        }

        [Test]
        public void TestDirectivesOverride()
        {
            string csv = "#class:MyName\nid,name\n1,Item";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var settings = GetDefaultSettings();
            settings.ClassName = "DefaultName";
            var schema = SchemaBuilder.Build(rawData, settings);
            
            Assert.AreEqual("MyName", schema.ClassName);
        }

        [Test]
        public void TestDuplicateHeaders()
        {
            string csv = "a,b,a\n1,2,3";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.Columns.Length);
            Assert.AreEqual("a", schema.Columns[0].OriginalHeader);
            Assert.AreEqual("a_2", schema.Columns[2].OriginalHeader);
            Assert.IsTrue(schema.Warnings.Any(w => w.message.Contains("Duplicate")));
        }

        [Test]
        public void TestEmptyHeader()
        {
            string csv = ",name,\n1,Item,3";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual("column_0", schema.Columns[0].OriginalHeader);
            Assert.AreEqual("column_2", schema.Columns[2].OriginalHeader);
            Assert.IsTrue(schema.Warnings.Any(w => w.message.Contains("Empty header")));
        }

        [Test]
        public void TestUnrecognizedType()
        {
            string csv = "id,position\nint,vectr3\n1,(1,2,3)";
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.String, schema.Columns[1].Type);
            Assert.IsTrue(schema.Warnings.Any(w => w.message.Contains("Unrecognized") || w.message.Contains("vectr3")));
        }
    }
}
