using NUnit.Framework;
using DataToScriptableObject;
using DataToScriptableObject.Editor;
using System.Linq;

namespace DataToScriptableObject.Tests.Editor
{
    public class SchemaBuilderTests
    {
        private GenerationSettings GetDefaultSettings()
        {
            return new GenerationSettings
            {
                sanitizeFieldNames = true,
                nullToken = "null",
                arrayDelimiter = ";",
                useListInsteadOfArray = false,
                useSerializeField = false,
                generateCreateAssetMenu = true,
                addAutoGeneratedHeader = true
            };
        }

        [Test]
        public void TestBasicThreeRowHeader()
        {
            string csv = "id,name,damage\nint,string,float\nkey,name,\n1,Sword,15.5";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.columns.Length);
            Assert.AreEqual(ResolvedType.Int, schema.columns[0].resolvedType);
            Assert.AreEqual(ResolvedType.String, schema.columns[1].resolvedType);
            Assert.AreEqual(ResolvedType.Float, schema.columns[2].resolvedType);
            Assert.IsTrue(schema.columns[0].isKey);
            Assert.IsTrue(schema.columns[1].isName);
        }

        [Test]
        public void TestSingleRowHeader()
        {
            string csv = "id,name,value\n1,Item,100";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.columns.Length);
            Assert.AreEqual(ResolvedType.Int, schema.columns[0].resolvedType);
            Assert.AreEqual(ResolvedType.String, schema.columns[1].resolvedType);
            Assert.AreEqual(ResolvedType.Int, schema.columns[2].resolvedType);
        }

        [Test]
        public void TestTwoRowHeader()
        {
            string csv = "id,name,value\nint,string,float\n1,Item,10.5";
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.columns.Length);
            Assert.AreEqual(ResolvedType.Int, schema.columns[0].resolvedType);
            Assert.AreEqual(ResolvedType.String, schema.columns[1].resolvedType);
            Assert.AreEqual(ResolvedType.Float, schema.columns[2].resolvedType);
        }

        [Test]
        public void TestEnumParsing()
        {
            string csv = "id,element\nint,enum\n,Fire,Water,Earth\n1,Fire";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.Enum, schema.columns[1].resolvedType);
            Assert.IsNotNull(schema.columns[1].enumValues);
            Assert.AreEqual(3, schema.columns[1].enumValues.Length);
            Assert.Contains("Fire", schema.columns[1].enumValues);
            Assert.Contains("Water", schema.columns[1].enumValues);
            Assert.Contains("Earth", schema.columns[1].enumValues);
        }

        [Test]
        public void TestRangeParsing()
        {
            string csv = "id,damage\nint,float\n,range(0;100)\n1,50";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.columns[1].attributes.ContainsKey("range"));
            Assert.AreEqual("0,100", schema.columns[1].attributes["range"]);
        }

        [Test]
        public void TestTooltipParsing()
        {
            string csv = "id,damage\nint,float\n,tooltip(Base damage)\n1,50";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.columns[1].attributes.ContainsKey("tooltip"));
            Assert.AreEqual("Base damage", schema.columns[1].attributes["tooltip"]);
        }

        [Test]
        public void TestSkipColumn()
        {
            string csv = "id,temp,name\nint,string,string\n,skip,\n1,ignore,Item";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.columns[1].isSkipped);
        }

        [Test]
        public void TestKeyAndName()
        {
            string csv = "id,name\nint,string\nkey,name\n1,Item";
            var rawData = CSVReader.Parse(csv, ",", "#", 3);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.IsTrue(schema.columns[0].isKey);
            Assert.IsTrue(schema.columns[1].isName);
        }

        [Test]
        public void TestDirectivesOverride()
        {
            string csv = "#class:MyName\nid,name\n1,Item";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var settings = GetDefaultSettings();
            settings.className = "DefaultName";
            var schema = SchemaBuilder.Build(rawData, settings);
            
            Assert.AreEqual("MyName", schema.className);
        }

        [Test]
        public void TestDuplicateHeaders()
        {
            string csv = "a,b,a\n1,2,3";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(3, schema.columns.Length);
            Assert.AreEqual("a", schema.columns[0].originalHeader);
            Assert.AreEqual("a_2", schema.columns[2].originalHeader);
            Assert.IsTrue(schema.warnings.Any(w => w.message.Contains("Duplicate")));
        }

        [Test]
        public void TestEmptyHeader()
        {
            string csv = ",name,\n1,Item,3";
            var rawData = CSVReader.Parse(csv, ",", "#", 1);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual("column_0", schema.columns[0].originalHeader);
            Assert.AreEqual("column_2", schema.columns[2].originalHeader);
            Assert.IsTrue(schema.warnings.Any(w => w.message.Contains("Empty header")));
        }

        [Test]
        public void TestUnrecognizedType()
        {
            string csv = "id,position\nint,vectr3\n1,(1,2,3)";
            var rawData = CSVReader.Parse(csv, ",", "#", 2);
            var schema = SchemaBuilder.Build(rawData, GetDefaultSettings());
            
            Assert.AreEqual(ResolvedType.String, schema.columns[1].resolvedType);
            Assert.IsTrue(schema.warnings.Any(w => w.message.Contains("Unrecognized") || w.message.Contains("vectr3")));
        }
    }
}
