namespace DataToScriptableObject
{
    [System.Serializable]
    public class GenerationSettings
    {
        public string className;
        public string databaseName;
        public string namespaceName;
        public string scriptOutputPath = "Assets/Scripts/Generated/";
        public string assetOutputPath = "Assets/Data/";
        public string assetPrefix = "";
        public bool useListInsteadOfArray = true;
        public bool generateDatabaseContainer = true;
        public bool generateEnumScripts = false;
        public bool overwriteExistingAssets = true;
        public bool deleteOrphanedAssets = false;
        public bool sanitizeFieldNames = true;
        public bool useSerializeField = false;
        public bool generatePropertyAccessors = false;
        public bool generateTooltips = false;
        public bool generateCreateAssetMenu = false;
        public bool serializableClassMode = false;
        public bool addAutoGeneratedHeader = true;
        public string assetNamingColumn = null;
        public string arrayDelimiter = ";";
        public string nullToken = "null";
        public string commentPrefix = "#";
        public int headerRowCount = 3;
    }
}
