namespace DataToScriptableObject
{
    [System.Serializable]
    public class GenerationSettings
    {
        public string ClassName { get; set; }
        public string DatabaseName { get; set; }
        public string NamespaceName { get; set; }
        public string ScriptOutputPath { get; set; } = "Assets/Scripts/Generated/";
        public string AssetOutputPath { get; set; } = "Assets/Data/";
        public string AssetPrefix { get; set; } = "";
        public bool UseListInsteadOfArray { get; set; } = true;
        public bool GenerateDatabaseContainer { get; set; } = true;
        public bool GenerateEnumScripts { get; set; } = false;
        public bool OverwriteExistingAssets { get; set; } = true;
        public bool DeleteOrphanedAssets { get; set; } = false;
        public bool SanitizeFieldNames { get; set; } = true;
        public bool UseSerializeField { get; set; } = false;
        public bool GeneratePropertyAccessors { get; set; } = false;
        public bool GenerateTooltips { get; set; } = false;
        public bool GenerateCreateAssetMenu { get; set; } = false;
        public bool SerializableClassMode { get; set; } = false;
        public bool AddAutoGeneratedHeader { get; set; } = true;
        public string AssetNamingColumn { get; set; } = null;
        public string ArrayDelimiter { get; set; } = ";";
        public string NullToken { get; set; } = "null";
        public string CommentPrefix { get; set; } = "#";
        public int HeaderRowCount { get; set; } = 3;
    }
}
